### ISSUE TITLE
Automatic 1111 freeze

### ISSUE THREAD

**Issue by tritant** [AIrjen/OneButtonPrompt#141]
Hello, I just found a situation where your extension crashes automatic 1111.
I gave external access to a friend via internet (myip:7860) with the --listen --share startup options in web-ui.bat.
Unfortunately, when me and my friend use your extension at the same time it crashes automatic 1111 which freezes completely.
If we use it separately, everything goes well with your extension which is wonderful.
Thx for your great work.

**Comment by AIrjen** [comment]
Hi! Well, this is certainly a use case I never tested. The easiest solution would be for your friend to buy his own hardware ;)

I am not sure why it happens, can you share something from the log, or explain how One Button Prompt is used?
Using One Button Run and Upscale at the same time would probably not work.

There is no reasons why using it with normal generation it would crash, I think... It might just be that it just doesn't work, with the way the A1111 handles scripts.
Does the same error occur for example when using other scripts?

If you have any more info, that would be helpful. I am unsure if there is anything I can do.

**Comment by tritant** [comment]
Hello, I am using the latest version automatic1111(1.6.0) with a lot of extensions, controlnet, faceswap, stable-diffusion-webui-rembg, sd-webui-prompt-all-in-one and others.
I have never had a crash with my rtx 4060ti with 16gb of ram, I generate at least 100 images per day.

I just noticed that even when I am alone on the PC the problem is also present.
I use the workflow assist with the promt variance =4, I generate the prompts, send prompts up and generate image again and again...
The crash is random, it can occur after 20 image generation or after 100 image generation.

When this happens, the console hangs on :

Creating a prompt variation

Critical hit! Something unique has been added to the prompt

and it is no longer possible to do anything except restart automatic 1111.

I tested several things.
A fork 26 commit behind your main branch, the problem is not present, it never crashes.
And now I have been testing your main branch for several hours with only one file changed.
I just replaced the build_dynamic_prompt.py file with that of the fork. https://github.com/5l1v3r1/OneButtonPrompt
For the moment I no longer have any crashes.

**Comment by AIrjen** [comment]
I've pushed a fix! Please get latest version, it should solve your problem.

If you want to know, I forgot to place a comma somewhere... :(

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/9aefd6ce-326a-4b48-a8cb-092057b97a9e)

It was this little one.

I'll try to be more careful next releases with prompt variant mode. I usually do like 10-20 runs but I should increase that by a lot to test properly on release.

Sorry, and I hope you have fun!

**Comment by tritant** [comment]
Hello, I have installed the latest version and I will test for hours.
Thank you very much for your wonderful work, it is by far the best promt generator in the world ;) and I have a lot of fun with it. 
I will come back to you if I still have problems.
